import { formatFailureBlock } from '../parser.js';

/**
 * @param {object} opts
 * @param {boolean} opts.passed
 * @param {number} opts.healCount
 * @param {import('../parser.js').ParseResult|null} [opts.lastResult]
 * @param {{ route: string, flowKind?: string }[]} [opts.routes]
 * @param {{ route: string, flowKind: string }[]} [opts.flows]
 * @param {string} [opts.framework]
 * @param {string} [opts.baseUrl]
 * @param {string[]} [opts.changedFiles]
 */
export function buildVerificationReport(opts) {
  const {
    passed,
    healCount,
    lastResult,
    routes = [],
    flows = [],
    framework = 'unknown',
    baseUrl = '',
    changedFiles = [],
  } = opts;

  const status = passed ? '✅ Passed' : '❌ Failed';
  const lines = [
    '# fixloop — Verification Report',
    '',
    `| Field | Value |`,
    `| --- | --- |`,
    `| Status | ${status} |`,
    `| Framework | \`${framework}\` |`,
    `| Base URL | \`${baseUrl || 'n/a'}\` |`,
    `| Heal iterations | ${healCount} |`,
    `| Routes discovered | ${routes.length} |`,
    ...(opts.triage?.label
      ? [`| Triage | \`${opts.triage.label}\` |`]
      : []),
    '',
  ];

  if (flows.length > 0) {
    lines.push('## Discovered flows', '');
    for (const f of flows) {
      lines.push(`- **${f.flowKind}** — \`${f.route}\` (${f.file})`);
    }
    lines.push('');
  }

  if (lastResult && lastResult.outcome !== 'passed') {
    lines.push('## Failure trace', '', '```json', formatFailureBlock(lastResult), '```', '');
    if (lastResult.runEnd?.summary) {
      lines.push(`**Summary:** ${lastResult.runEnd.summary}`, '');
    }
  }

  if (lastResult?.steps?.length) {
    lines.push('## Steps', '');
    for (const s of lastResult.steps) {
      const icon = s.status === 'passed' ? '✓' : '✗';
      lines.push(`- ${icon} Step ${s.step}: ${s.remark ?? s.status}`);
    }
    lines.push('');
  }

  if (changedFiles.length > 0) {
    lines.push('## Changed files', '');
    for (const f of changedFiles) lines.push(`- \`${f}\``);
    lines.push('');
  }

  lines.push(
    '---',
    '',
    '*Generated by [fixloop](https://github.com/abhiyansingh12/fixloop). Draft PR only after a green re-run. No auto-merge.*',
  );

  return lines.join('\n');
}

/**
 * @param {object} analysis
 */
export function buildAnalysisJson(analysis) {
  return JSON.stringify(
    {
      generatedAt: new Date().toISOString(),
      ...analysis,
    },
    null,
    2,
  );
}
